# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7657722679147f1dc39a830bcba153a2cedeed1fad5c2584c7999319811bb3a3462e0fc2109c681bf21f0d626b713b80df2d7f5911c0bdd44afbd3e1e6cf1ca2

test:
  secret_key_base: 3f6dcd5089787c813c471191fd26ce3eb8480ca3470f43b8c3438c1205cd2f72a84e0df3a3898ee62d11d13dac60d61a2d95eb7e0141b088c41dfe2049dc5641

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
